export const REQUEST_LOADING = "REQUEST_LOADING";
export const REQUEST_SUCCESS = "REQUEST_SUCCESS";
export const REQUEST_FAILED = "REQUEST_FAILED";
export const FEATURED_LOADING = "REQUEST_LOADING";
export const FEATURED_SUCCESS = "REQUEST_SUCCESS";
export const FEATURED_FAILED = "REQUEST_FAILED";
